#ifndef TRANSPORT_H
#define TRANSPORT_H

enum{
    ME_KEYUP =	1,
    ME_KEYDOWN,
    ME_HITEVENT,
    ME_TIMER,
    ME_DRAW,
    ME_CREATE,
    ME_MOUSECLICK,
    ME_MOUSEMOVE
};

enum{
    SE_MODECAMERAMOVE =	101,
    SE_CLOSEAFTER,
    SE_ADDVIRUS1,
    SE_ADDVIRUS2,
    SE_DELVIRUS,
    SE_MOUSECLICK,
    SE_VIRADDGOOD
};

enum{
    STO_SYSTEM	=	0,
    STO_MENU,
    STO_BACKGROUND,
    STO_FONTVIRUS,
    STO_POLE,
    STO_VIRUS
};

enum{
    ID_BMP_EMPTY	=	0,
    ID_BMP_BACKGROUND,
    ID_BMP_REDCELL,
    ID_BMP_GREENCELL,
    ID_BMP_SELREDCELL,
    ID_BMP_SELGREENCELL,
    ID_BMP_MENUSTART,
    ID_BMP_MENUEXIT,
    ID_BMP_PLAYERSNAMES,
    ID_BMP_ALIVEVIR1,
    ID_BMP_ADDING1,
    ID_BMP_KILLING1,
    ID_BMP_DEADVIR1,
    ID_BMP_ALIVEVIR2,
    ID_BMP_ADDING2,
    ID_BMP_KILLING2,
    ID_BMP_DEADVIR2,
    NumBmpRes
};

#endif // TRANSPORT_H
